server:
  port: 9011
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/hero_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hero@202207
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
workerId: 0
datacenterId: 0
